workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Ensure Flutter project structure
        script: |
          echo "Running flutter create to generate missing android/ios files if needed"
          flutter create .
      - name: Clean build cache
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK (release)
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - build