name: cheese_for_everyone
description: A chess app with AI, assistant, and local modes
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Chess logic and UI
  chess: ^0.8.1
  flutter_chess_board: ^1.0.1

  # Speech recognition & TTS
  speech_to_text: ^7.3.0
  flutter_tts: ^3.5.2

  # WebSocket communication
  web_socket_channel: ^2.3.0

  # Icons & UI support
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true